name: Security [Secrets Scan]

env:
  REPORT_NAME: secret-detection-report.json

on: [push, pull_request]

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Scan repository for secrets with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: json
          output: "${{ env.REPORT_NAME }}"
          exit-code: 0
          scanners: secret

      - name: Check for secrets
        run: |
          secrets_count=$(jq '.Results[].Vulnerabilities | length' "${{ env.REPORT_NAME }}" | awk '{s+=$1} END {print s}')
          if [ "$secrets_count" -gt 0 ]; then
            echo "::error::Found $secrets_count secrets in repository (see "${{ env.REPORT_NAME }}")"
          fi
      
      - name: Upload report (private)
        uses: actions/upload-artifact@v4
        with:
          name: secret-detection-report
          path: "${{ env.REPORT_NAME }}"
          retention-days: 30
    
    #   - name: Send secrets report
    #     run: |
    #       curl -X POST \
    #         -H "Content-Type: application/json" \
    #         -d @"${{ env.REPORT_NAME }}" \
    #         "${{ secrets.WEBHOOK_URL }}"
